regexp: rename from regex.
Fixes:

    $ cppcheck regex.c
    Checking regex.c ...
    regex.h:22:0: error: #include nested too deeply [preprocessorErrorDirective]